export enum USER_ROLES {
  SUPER_ADMIN = 'SUPER_ADMIN',
  ADMIN = 'ADMIN',
  USER = 'USER',
  CITIZEN = 'CITIZEN',
  ATTORNEY = 'ATTORNEY',
  MENTAL_HEALTH_PROFESSIONAL = 'MENTAL_HEALTH_PROFESSIONAL',
  POLICE = 'POLICE',
  BAIL_BONDSMAN = 'BAIL_BONDSMAN',
}
